//src/app/routes/pageRouteMap.ts
export const pageRouteMap = [
  { page: 'HomeLandingPage', feature: 'home', path: '/', title: 'Trang chủ IX' },
  { page: 'HomeProgramsPage', feature: 'home', path: '/gioi-thieu', title: 'Chương trình học iX' },
  { page: 'CourseListPage', feature: 'course', path: '/courses', title: 'Danh sách khóa học' },
  { page: 'CourseDetailPage', feature: 'course', path: '/courses/:courseId', title: 'Chi tiết khóa học' },
  { page: 'LessonPage', feature: 'learning', path: '/learning/lesson/:lessonId', title: 'Bài học trực tuyến' },
  { page: 'QuizPage', feature: 'learning', path: '/learning/quiz/:quizId', title: 'Làm bài trắc nghiệm' },
  { page: 'QuizResultPage', feature: 'learning', path: '/learning/quiz/:quizId/result', title: 'Chi tiết kết quả Quiz' },
  { page: 'HomeworkUploadPage', feature: 'submission', path: '/submission/upload', title: 'Nộp ảnh bài làm tự luận' },
  { page: 'HomeworkGalleryPage', feature: 'submission', path: '/submission/gallery', title: 'Quản lý ảnh bài làm' },
  { page: 'HomeworkViewSubmittedPage', feature: 'submission', path: '/submission/view/:submissionId', title: 'Bài làm đã nộp' },
  { page: 'HomeworkResultPage', feature: 'submission', path: '/submission/result/:submissionId', title: 'Kết quả bài tập' },
  { page: 'SubmissionSuccessPage', feature: 'submission', path: '/submission/success', title: 'Nộp bài thành công' },
  { page: 'PauseSuccessPage', feature: 'submission', path: '/submission/pause-success', title: 'Đã tạm dừng bài làm' },
  { page: 'StudentDashboardPage', feature: 'dashboard', path: '/dashboard/student', title: 'Dashboard học sinh' },
  { page: 'ParentDashboardPage', feature: 'dashboard', path: '/dashboard/parent', title: 'Dashboard phụ huynh' },
  { page: 'TeacherDashboardPage', feature: 'teacher', path: '/teacher/dashboard', title: 'Dashboard giáo viên' },
  { page: 'WeeklyReviewPage', feature: 'teacher', path: '/teacher/reviews/:reviewId', title: 'Đánh giá tuần' },
  { page: 'RankingClassPage', feature: 'ranking', path: '/ranking/class', title: 'Bảng xếp hạng lớp' },
  { page: 'RankingRegionPage', feature: 'ranking', path: '/ranking/region', title: 'Bảng xếp hạng khu vực' },
  { page: 'RankingNationalPage', feature: 'ranking', path: '/ranking/national', title: 'Bảng xếp hạng toàn quốc' },
  { page: 'RegisterPage', feature: 'auth', path: '/auth/register', title: 'Tạo tài khoản' },
  { page: 'RegisterCompactPage', feature: 'auth', path: '/auth/register-compact', title: 'Tạo tài khoản nhanh' },
  { page: 'ForgotPasswordPage', feature: 'auth', path: '/auth/forgot-password', title: 'Quên mật khẩu' },
  {
    page: 'StudentVideoTaskContentPage',
    feature: 'student',
    path: '/student/classes/:classCode/tasks/:taskCode/video',
    title: 'Nội dung nhiệm vụ video',
  },
  {
    page: 'StudentFileTaskContentPage',
    feature: 'student',
    path: '/student/classes/:classCode/tasks/:taskCode/file',
    title: 'Nội dung nhiệm vụ file',
  },
  {
    page: 'StudentQuizTaskContentPage',
    feature: 'student',
    path: '/student/classes/:classCode/tasks/:taskCode/quiz',
    title: 'Nội dung nhiệm vụ quiz',
  },
] as const
